# Generated by Django 5.2.6 on 2025-09-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('phone_numbers', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('structure', models.TextField(max_length=120, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Прямой эфир',
                'verbose_name_plural': 'Прямые эфиры',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('payment_method', models.CharField(max_length=10, verbose_name='Метод оплаты')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.clients', verbose_name='Клиент')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.dishes', verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Dishes_Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('id_checks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.checks', verbose_name='Чек')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.dishes', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Блюдо в чеке',
                'verbose_name_plural': 'Блюда в чеке',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.clients', verbose_name='Клиент')),
                ('id_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.events', verbose_name='Мероприятия')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='id_lives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.lives', verbose_name='Прямой эфир с мероприятия'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=20, verbose_name='Категории')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.dishes', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('passport', models.CharField(unique=True, verbose_name='Паспорт')),
                ('id_professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Work_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.events', verbose_name='Мероприятие')),
                ('id_workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.workers', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Работник на мероприятии',
                'verbose_name_plural': 'Работники на мероприятиях',
            },
        ),
        migrations.AddField(
            model_name='checks',
            name='id_workers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.workers', verbose_name='Работник'),
        ),
    ]
