# Generated by Django 5.2.7 on 2025-11-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=20, verbose_name='Price')),
                ('structure', models.TextField(max_length=120, verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, upload_to='Jazz_events/', verbose_name='Foto')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='End')),
                ('dress', models.CharField(choices=[('No dress code', 'No dress code'), ('Dress code Retro 1920s', 'Dress code Retro 1920s'), ('Dress code Retro 1950s', 'Dress code Retro 1950s'), ('Formal wear', 'Formal wear'), ('Like going to a ball', 'Like going to a ball')], default='No dress code', max_length=90, verbose_name='Dress code')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=20, verbose_name='Price')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('status', models.CharField(choices=[('Live', 'Live'), ('None', 'None')], max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=15, verbose_name='Name')),
                ('surname', models.CharField(default='Null', max_length=15, verbose_name='Surname')),
                ('middle_name', models.CharField(default='Null', max_length=15, verbose_name='Middle name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('phone_numbers', models.CharField(max_length=12, unique=True, verbose_name='Phone number')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['surname', 'name'],
                'indexes': [models.Index(fields=['surname'], name='jazz_app_cl_surname_7113a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('payment_method', models.CharField(max_length=10, verbose_name='Payment method')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.clients', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='Dishes_Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('id_checks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.checks', verbose_name='Check')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.dishes', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Dish on the check',
                'verbose_name_plural': 'Dishes in checks',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.clients', verbose_name='Client')),
                ('id_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.events', verbose_name='Events')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='id_lives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jazz_app.lives', verbose_name='Live from the event'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=20, verbose_name='Categories')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.dishes', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=15, verbose_name='Name')),
                ('surname', models.CharField(default='Null', max_length=15, verbose_name='Surname')),
                ('middle_name', models.CharField(default='Null', max_length=15, verbose_name='Middle name')),
                ('birthday', models.DateField(verbose_name='Иirthday')),
                ('passport', models.CharField(unique=True, verbose_name='Passport')),
                ('id_professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.professions', verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Work_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.events', verbose_name='Event')),
                ('id_workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Worker at an event',
                'verbose_name_plural': 'Workers at events',
            },
        ),
        migrations.AddField(
            model_name='checks',
            name='id_workers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazz_app.workers', verbose_name='Worker'),
        ),
        migrations.AddIndex(
            model_name='workers',
            index=models.Index(fields=['surname'], name='jazz_app_wo_surname_9ee0bc_idx'),
        ),
    ]
