# Generated by Django 5.2.7 on 2025-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='artists_img',
            field=models.ImageField(default=None, upload_to='Jazz_events/', verbose_name='Artists'),
        ),
        migrations.AddField(
            model_name='events',
            name='artists_name',
            field=models.CharField(default='Name', max_length=50, verbose_name='Star name'),
        ),
        migrations.AddField(
            model_name='events',
            name='discription',
            field=models.CharField(default=None, max_length=200, verbose_name='Description'),
        ),
    ]
