# Generated by Django 5.2.6 on 2025-09-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0002_alter_clients_phone_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='id_dishes',
        ),
    ]
