# Generated by Django 5.2.7 on 2025-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0002_events_artists_img_events_artists_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='id_clients',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='id_events',
        ),
        migrations.RemoveField(
            model_name='work_events',
            name='id_events',
        ),
        migrations.RemoveField(
            model_name='work_events',
            name='id_workers',
        ),
        migrations.RenameField(
            model_name='checks',
            old_name='id_clients',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='checks',
            old_name='id_workers',
            new_name='worker_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='id_lives',
            new_name='live_id',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='id_dishes',
            new_name='dish_id',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='id_professions',
            new_name='profession_id',
        ),
        migrations.AddField(
            model_name='checks',
            name='dishes',
            field=models.ManyToManyField(to='jazz_app.dishes'),
        ),
        migrations.AddField(
            model_name='clients',
            name='events',
            field=models.ManyToManyField(to='jazz_app.events'),
        ),
        migrations.AddField(
            model_name='events',
            name='workers',
            field=models.ManyToManyField(to='jazz_app.workers'),
        ),
        migrations.DeleteModel(
            name='Dishes_Checks',
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
        migrations.DeleteModel(
            name='Work_Events',
        ),
    ]
