# Generated by Django 5.2.7 on 2025-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0003_remove_guests_id_clients_remove_guests_id_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
