# Generated by Django 5.2.6 on 2025-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0003_remove_checks_id_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='full_name',
        ),
        migrations.AddField(
            model_name='clients',
            name='middle_name',
            field=models.CharField(default='Null', max_length=10, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default='Null', max_length=10, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='clients',
            name='surname',
            field=models.CharField(default='Null', max_length=10, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='workers',
            name='middle_name',
            field=models.CharField(default='Null', max_length=10, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='workers',
            name='name',
            field=models.CharField(default='Null', max_length=10, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='workers',
            name='surname',
            field=models.CharField(default='Null', max_length=10, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='lives',
            name='status',
            field=models.CharField(choices=[('В эфире', 'В эфире'), ('Не в эфире', 'Не в эфире')], max_length=10, verbose_name='Статус'),
        ),
    ]
