# Generated by Django 5.2.6 on 2025-09-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz_app', '0004_remove_clients_full_name_remove_workers_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='middle_name',
            field=models.CharField(default='Null', max_length=15, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(default='Null', max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(default='Null', max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='middle_name',
            field=models.CharField(default='Null', max_length=15, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(default='Null', max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='surname',
            field=models.CharField(default='Null', max_length=15, verbose_name='Фамилия'),
        ),
    ]
